// <auto-generated />
namespace CarVehicle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class bmjobaer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bmjobaer));
        
        string IMigrationMetadata.Id
        {
            get { return "201706121344169_bmjobaer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
